### ISSUE TITLE
几个优化建议

### ISSUE THREAD

**Issue by zhufeizzz** [houbb/junitperf#10]
1、Console日志打印的时候显示测试方法名称，现在合起来看不方便
2、Html报告的右上角灰色方法名只能显示20个字符，多了会被隐藏
3、建议Html报告左侧列表能固定，便于切换

**Comment by houbb** [comment]
v2.0.6 已优化 1 2 3

对于报告顺序，已在 [指定方法执行顺序](https://github.com/houbb/junitperf#%E6%8C%87%E5%AE%9A%E6%96%B9%E6%B3%95%E6%89%A7%E8%A1%8C%E9%A1%BA%E5%BA%8F) 中说明。
